name: Build Cython

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython setuptools

    - name: Compile
      run: |
        python -c "from setuptools import setup; from Cython.Build import cythonize; setup(ext_modules=cythonize('wifihack.py'))" build_ext --inplace

    - name: Upload SO files
      uses: actions/upload-artifact@v4
      with:
        name: cython-so
        path: *.so
